// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcjdJI_ldQagwu3eTy8352Du0mIgtuZkg',
    appId: '1:708484069918:web:5396c8a7f64e06697f4c0f',
    messagingSenderId: '708484069918',
    projectId: 'crud-firebase-ca049',
    authDomain: 'crud-firebase-ca049.firebaseapp.com',
    storageBucket: 'crud-firebase-ca049.appspot.com',
    measurementId: 'G-LDJ89CZDYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsKL5oosNHK1Wsv7zu551odNniughVurQ',
    appId: '1:708484069918:android:96c01b47863dedcb7f4c0f',
    messagingSenderId: '708484069918',
    projectId: 'crud-firebase-ca049',
    storageBucket: 'crud-firebase-ca049.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBULM3vIPJcFZ3E5zVLE82849QDoPHyP00',
    appId: '1:708484069918:ios:667d7160bf2ca3b97f4c0f',
    messagingSenderId: '708484069918',
    projectId: 'crud-firebase-ca049',
    storageBucket: 'crud-firebase-ca049.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBULM3vIPJcFZ3E5zVLE82849QDoPHyP00',
    appId: '1:708484069918:ios:123a54637d4440f37f4c0f',
    messagingSenderId: '708484069918',
    projectId: 'crud-firebase-ca049',
    storageBucket: 'crud-firebase-ca049.appspot.com',
    iosBundleId: 'com.example.crudFirebase.RunnerTests',
  );
}
